services:
  zenoh:
    command: -c /zenoh-config.json5
    environment:
      RUST_LOG: zenoh=info
    image: eclipse/zenoh:0.10.1-rc
    container_name: "fms-zenoh-router"
    networks:
    - "fms-backend"
    - "fms-vehicle"
    ports:
    - 7447:7447/tcp
    - 1883:1883/tcp
    - 8000:8000/tcp
    restart: unless-stopped
    volumes:
    - ./zenoh-config.json5:/zenoh-config.json5
  fms-forwarder:
    command: "zenoh -m client"
